language: java
env:
  - TEST_SUITE=units
  - TEST_SUITE=integration
jdk:
  - oraclejdk8
  - oraclejdk7
#  - oraclejdk6
  - openjdk6
  - openjdk7
#  - openjdk8

script: ant 

branches:
  only:
  - master
notifications:
  email:
  - loebnert@gmail.com
