language: java
install: ant deps
jdk:
  - oraclejdk8
  - oraclejdk7
  - oraclejdk6
  - openjdk6
  - openjdk7
matrix:
  include:
  - jdk: oraclejdk7
    script: ant
  - jdk: oraclejdk8
    script: ant
  - jdk: oraclejdk6
    script: ant
  - jdk: openjdk7
    script: ant
  - jdk: openjdk6
    script: ant

branches:
  only:
  - master
notifications:
  email:
  - loebnert@gmail.com
